version: '3'
services:
  prometheus:
    image: prom/prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
#      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
#      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
#      - GF_LOG_FILTERS=rendering:debug
    volumes:
       - ./datasources:/etc/grafana/provisioning/datasources
       - ./dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - prometheus
#  renderer:
#    image: grafana/grafana-image-renderer:latest
#    ports:
#      - 8081:8081