version: '2.1'
services:
  mongodb:
    image: mongo:4.4.4-bionic
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
  rabbitmq:
    container_name: rabbitmq
    image: lfeoperatorfabric/of-rabbitmq:4.2.0.RELEASE
    ports:
      - "5672:5672"
      - "15672:15672"
  keycloak:
    image: keycloak/keycloak:23.0.7
    command:
      - -v
      - start-dev 
      - --import-realm
    environment:
      - KC_HTTP_PORT=89
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HTTP_RELATIVE_PATH=/auth
    volumes:
    - ./realms/export:/opt/keycloak/data/import
    ports:
    - "89:89"
  users:
    container_name: users
    image: "lfeoperatorfabric/of-users-service:4.2.0.RELEASE"
    depends_on:
      - mongodb
      - rabbitmq
    user: ${USER_ID}:${USER_GID}
    ports:
     - "2103:2103"
     - "4103:5005"
    environment:
    - REGISTRY_HOST=registry
    - REGISTRY_PORT=8080
    - DEPENDS_ON=CONFIG
    volumes:
      - "../certificates:/certificates_to_add"
      - "./docker-configurations/users.yml:/config/application.yml"
      - "./docker-configurations/common.yml:/config/common.yml"
  businessconfig:
    container_name: businessconfig
    image: "lfeoperatorfabric/of-businessconfig-service:4.2.0.RELEASE"
    depends_on:
      - mongodb
    user: ${USER_ID}:${USER_GID}
    ports:
     - "2100:2100"
     - "4100:5005"
    environment:
    - REGISTRY_HOST=registry
    - REGISTRY_PORT=8080
    - DEPENDS_ON=CONFIG
    volumes:
      - "../certificates:/certificates_to_add"
      - "./businessconfig-storage:/businessconfig-storage"
      - "./docker-configurations/common.yml:/config/common.yml"
      - "./docker-configurations/businessconfig.yml:/config/application.yml"
  cards-publication:
    container_name: cards-publication
    image: "lfeoperatorfabric/of-cards-publication-service:4.2.0.RELEASE"
    depends_on:
      - mongodb
      - rabbitmq
    user: ${USER_ID}:${USER_GID}
    ports:
     - "2102:2102"
     - "4102:5005"
    environment:
    - REGISTRY_HOST=registry
    - REGISTRY_PORT=8080
    - DEPENDS_ON=CONFIG
    volumes:
      - "../certificates:/certificates_to_add"
      - "./docker-configurations/common.yml:/config/common.yml"
      - "./docker-configurations/cards-publication.yml:/config/application.yml"
  cards-consultation:
    container_name: cards-consultation
    image: "lfeoperatorfabric/of-cards-consultation-service:4.2.0.RELEASE"
    depends_on:
      - mongodb
      - rabbitmq
    user: ${USER_ID}:${USER_GID}
    ports:
     - "2104:2104"
     - "4104:5005"
    environment:
    - REGISTRY_HOST=registry
    - REGISTRY_PORT=8080
    - DEPENDS_ON=CONFIG
    volumes:
      - "../certificates:/certificates_to_add"
      - "./docker-configurations/common.yml:/config/common.yml"
      - "./docker-configurations/cards-consultation.yml:/config/application.yml"
  web-ui:
    image: "lfeoperatorfabric/of-web-ui:4.2.0.RELEASE"
    ports:
    - "2002:80"
    depends_on:
      - users
      - businessconfig
      - cards-consultation
    volumes:
      - "./web-ui.json:/usr/share/nginx/html/config/web-ui.json"
      - "./ui-menu.json:/usr/share/nginx/html/config/ui-menu.json"
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
