{
 "title": "Opfab dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Backend services",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(instance) (increase(http_server_requests_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cards publication",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "floor(increase(http_server_requests_seconds_count{instance=\"172.17.0.1:2102\", method=\"POST\", uri=~\"/cards\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cards consultation memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(jvm_memory_used_bytes{instance=\"172.17.0.1:2103\"})/1024",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}