on:
  push:
  pull_request:

jobs:
  CypressTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3.7.0
      
      - name: Install Cypress Dependencies
        run: npm ci --prefix cypress

      - name: Cypress.io
        uses: cypress-io/github-action@v5.8.2
        with:
          command: npm run spec
