on:
  push:
  pull_request:

jobs:
  CypressTests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Start Opfab
        run: |
          cd server
          ./startServer.sh

      - name: Cypress Tests
        uses: cypress-io/github-action@v5.8.2
        with:
          working-directory: cypress
