on:
  push:

jobs:
  changed_files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37.4.0

      - name: echo changed files
        run: |
          cd .github/scripts
          ./licenceHeaderCheck.sh ${{ steps.changed-files.outputs.all_changed_files }}
