on:
  push:

jobs:
  check_copyright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37.4.0

      - name: Verify copyright header
        run: .github/scripts/licenceHeaderCheck.sh ${{ steps.changed-files.outputs.all_changed_files }}
